### PR TITLE
Feature/lagom/fixing password leak

### LINKED ISSUE #135: Possible Password Leak
## Problem
In the current implementation a big password leak could happen if an intruder is able to connect to Kafka.  
If he would subscribe to the AuthenticationTopic, he would get all users and corresponding passwords in plain text of the running session.

## Solution Attempt
- Create an intern endpoint in the AuthenticationService to add the user with his password (which only admin-accounts can use)
- Remove the AuthenticationTopic 
- If an user gets added, the UserService makes a direkt call to the AuthenticationService

### Problems with this attempt
- It would be overhead to have the change password in the UserService, it should be in the AuthenticationService
- The AuthenticationService gets more vulnerable (Possible solution: Traefik only forwards the exakt path to the change password endpoint)

## Side Notes
- The DeletionTopic is not affected, because it does not send any critical information

### LINKED ISSUE #140: Refactor password change functionality
Password changing should not be done via Kafka, as seen in the Issue. #135

### PR DESCRIPTION
**Pull request by ldklenner**
### Reason for this PR
- As described in Issue #135, sensitive password data should not be handled by Kafka message broker

### Changes in this PR
- Closes #135 
- Closes #140 
- Migrated password changing functionality into AuthenticationService
- UserService now directly calls the AuthenticationService

### CODE REVIEW

File: product_code/lagom/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala [hunk 1]
```diff
@@ -20,7 +21,17 @@ case class AuthenticationState(optEntry: Option[AuthenticationEntry]) {
    */
   def applyCommand(cmd: AuthenticationCommand): ReplyEffect[AuthenticationEvent, AuthenticationState] =
     cmd match {
-      case SetAuthentication(user, replyTo) => Effect.persist(OnSet(user)).thenReply(replyTo) { _ => Accepted }
+      case SetAuthentication(user, replyTo) =>
+
+        val validationErrors = user.validate.map(error => SimpleError("authUser." + error.name, error.reason))
```
Comment (dhelmert) [inline product_code/lagom/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala:26]: "authUser." is only the correct prefix when used in addUser, not in changePassword
